# Generated by Django 6.0.6 on 2026-07-26 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_ic_sp', '0002_load_ic_sp_seed_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicExaminerSP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('display_name', models.CharField(help_text='Nome completo ou forma abreviada exibida na assinatura do laudo.', max_length=255, verbose_name='Nome de exibição no laudo')),
                ('forensic_team', models.ForeignKey(help_text='Equipe de perícias criminalísticas à qual o perito está lotado.', on_delete=django.db.models.deletion.PROTECT, related_name='examiners', to='institution_ic_sp.forensicteam', verbose_name='Equipe pericial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_examiner_sp', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perito criminal (SP)',
                'verbose_name_plural': 'Peritos criminais (SP)',
                'ordering': ['display_name'],
            },
        ),
    ]
