# reportline/profiles/migrations/0002_forensic_examiner_sp_job_title.py
# Generated by Django 6.0.6 on 2026-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicexaminersp',
            name='job_title',
            field=models.CharField(blank=True, choices=[('perito_criminal', 'Perito Criminal'), ('desenhista_tecnico', 'Desenhista Técnico Pericial'), ('fotografo_tecnico', 'Fotógrafo Técnico Pericial')], help_text='Função exercida na equipe pericial.', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='forensicexaminersp',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nome completo ou forma abreviada exibida na assinatura do laudo.', max_length=255, verbose_name='Nome de exibição no laudo'),
        ),
    ]
