# reportline/profiles/migrations/0003_forensic_examiner_sp_nucleus_assignment.py
# Generated by Django 6.0.6 on 2026-07-30 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_ic_sp', '0004_forensicteam_address_and_more'),
        ('profiles', '0002_forensic_examiner_sp_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicexaminersp',
            name='forensic_nucleus',
            field=models.ForeignKey(blank=True, help_text='Use quando o servidor estiver lotado diretamente no núcleo, sem equipe pericial específica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_examiners', to='institution_ic_sp.forensicnucleus', verbose_name='Núcleo pericial'),
        ),
        migrations.AlterField(
            model_name='forensicexaminersp',
            name='forensic_team',
            field=models.ForeignKey(blank=True, help_text='Equipe de perícias criminalísticas à qual o servidor está lotado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examiners', to='institution_ic_sp.forensicteam', verbose_name='Equipe pericial'),
        ),
        migrations.AlterField(
            model_name='forensicexaminersp',
            name='job_title',
            field=models.CharField(blank=True, choices=[('perito_criminal', 'Perito Criminal'), ('desenhista_tecnico', 'Desenhista Técnico Pericial'), ('fotografo_tecnico', 'Fotógrafo Técnico Pericial')], help_text='Função exercida na lotação pericial.', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AddConstraint(
            model_name='forensicexaminersp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('forensic_nucleus__isnull', True), ('forensic_team__isnull', False)), models.Q(('forensic_nucleus__isnull', False), ('forensic_team__isnull', True)), _connector='OR'), name='forensic_examiner_sp_exactly_one_assignment'),
        ),
    ]
