# reportline/profiles/migrations/0005_forensicexaminersp_can_send_images_to_external_ai.py
# Generated by Django 6.0.6 on 2026-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_forensic_examiner_sp_preamble_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicexaminersp',
            name='can_send_images_to_external_ai',
            field=models.BooleanField(default=False, help_text='Autoriza o envio de fotografias do local a provedores externos de IA (OpenAI). Desabilitado por padrão.', verbose_name='Pode enviar imagens à IA externa'),
        ),
    ]
