# reportline/reportline/settings.py
"""
Django settings for reportline project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-5c&))li-$t3oy01p4e)4a@6b*%ti-5-rtri0rxze6i-$e=-p@g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# Instruções para o Django confiar nos cabeçalhos de Host e Proto vindos do Nginx/Cloudflare
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Lê FORCE_SCRIPT_NAME apenas se estiver definido no ambiente (Produção)
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', None)

# Configura o ALLOWED_HOSTS a partir da variável de ambiente
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,localhost:8000')
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_env.split(',') if host.strip()]

# Origens confiáveis para validação do token CSRF via HTTPS
_csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://pith.com.br,https://www.pith.com.br')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_env.split(',') if origin.strip()]

# Se FORCE_SCRIPT_NAME estiver ativo (/rln), amarra os cookies a esse subcaminho
if FORCE_SCRIPT_NAME:
    SESSION_COOKIE_PATH = FORCE_SCRIPT_NAME
    CSRF_COOKIE_PATH = FORCE_SCRIPT_NAME

# Segurança de Cookies em ambiente de Produção
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'

# Ajuste no STATIC_URL e MEDIA_URL para respeitar o prefixo do subcaminho se existir
if FORCE_SCRIPT_NAME:
    STATIC_URL = f'{FORCE_SCRIPT_NAME}/static/'
    MEDIA_URL = f'{FORCE_SCRIPT_NAME}/media/'
else:
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'common',
    'accounts',
    'institution_ic_sp',
    'profiles',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'reportline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.auth_settings',
                'institution_ic_sp.context_processors.forensic_examiner_context',
                'reports.context_processors.report_editor_dev',
            ],
        },
    },
]

WSGI_APPLICATION = 'reportline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'accounts:login'

AUTH_PROVIDER = os.getenv('AUTH_PROVIDER', 'local')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
FORENSIC_AI_MODEL = os.getenv('FORENSIC_AI_MODEL', 'gpt-4o-mini')
FORENSIC_AI_SANITIZATION_ENABLED = (
    os.getenv('FORENSIC_AI_SANITIZATION_ENABLED', 'true').lower() == 'true'
)
FORENSIC_AI_BLOCK_ON_RESIDUAL_PII = (
    os.getenv('FORENSIC_AI_BLOCK_ON_RESIDUAL_PII', 'true').lower() == 'true'
)
PRESIDIO_SPACY_MODEL = os.getenv('PRESIDIO_SPACY_MODEL', 'pt_core_news_lg')
FORENSIC_AI_SANITIZATION_ALLOWLIST = os.getenv('FORENSIC_AI_SANITIZATION_ALLOWLIST', '')

# Google Safe Browsing (moderação de links). Vazio = não usar.
GOOGLE_SAFE_BROWSING_API_KEY = os.getenv('GOOGLE_SAFE_BROWSING_API_KEY', '')

# Google Cloud Speech-to-Text v2 (ditado por voz). Project id vazio = desabilitado.
GOOGLE_CLOUD_PROJECT_ID = os.getenv('GOOGLE_CLOUD_PROJECT_ID', '')
GOOGLE_APPLICATION_CREDENTIALS_PATH = os.getenv('GOOGLE_APPLICATION_CREDENTIALS_PATH', '')
GOOGLE_SPEECH_STT_V2_LOCATION = os.getenv('GOOGLE_SPEECH_STT_V2_LOCATION', 'global')
GOOGLE_SPEECH_STT_V2_RECOGNIZER = os.getenv('GOOGLE_SPEECH_STT_V2_RECOGNIZER', '_')
GOOGLE_SPEECH_STT_V2_LANGUAGE_CODE = os.getenv('GOOGLE_SPEECH_STT_V2_LANGUAGE_CODE', 'pt-BR')
GOOGLE_SPEECH_STT_V2_MODEL = os.getenv('GOOGLE_SPEECH_STT_V2_MODEL', 'long')
GOOGLE_SPEECH_STT_V2_MAX_AUDIO_BYTES = int(
    os.getenv('GOOGLE_SPEECH_STT_V2_MAX_AUDIO_BYTES', str(10 * 1024 * 1024))
)

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.custom_social_account_adapter.CustomSocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}

STATICFILES_DIRS = [
    # pasta static global se for criada
    # os.path.join(BASE_DIR, 'static')
]