# reportline/common/migrations/0001_initial.py
# Generated by Django 6.0.6 on 2026-08-06 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0009_reportuserconfig_page_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSanitizationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('operation', models.CharField(help_text='Identificador da operação de IA (ex.: metadata_extraction).', max_length=64, verbose_name='Operação')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 do texto original antes da sanitização.', max_length=64, verbose_name='Hash do conteúdo')),
                ('replacement_counts', models.JSONField(default=dict, help_text='Contagem de substituições por tipo/categoria.', verbose_name='Substituições')),
                ('blocked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('block_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo do bloqueio')),
                ('provider', models.CharField(default='openai', max_length=32, verbose_name='Provedor')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='Modelo')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sanitization_audits', to='reports.report', verbose_name='Laudo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sanitization_audits', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria de sanitização para IA',
                'verbose_name_plural': 'Auditorias de sanitização para IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
