# Generated by Django 6.0.6 on 2026-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('govbr', 'gov.br')], default='local', max_length=20, verbose_name='Provedor de autenticação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='external_subject',
            field=models.CharField(blank=True, help_text="Valor estável do claim 'sub' retornado pelo provedor OAuth.", max_length=255, null=True, verbose_name='Identificador externo (OAuth)'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('external_subject__isnull', False)), fields=('auth_provider', 'external_subject'), name='unique_external_subject_per_provider'),
        ),
    ]
