# reportline/reports/migrations/0001_initial.py
# Generated by Django 6.0.6 on 2026-07-30 21:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('block_type', models.CharField(choices=[('heading', 'Título'), ('paragraph', 'Parágrafo'), ('link', 'Link'), ('ordered_list', 'Lista numerada'), ('unordered_list', 'Lista com marcadores'), ('table', 'Tabela'), ('image', 'Imagem')], max_length=30, verbose_name='Tipo de bloco')),
                ('content', models.JSONField(default=dict, help_text='Payload estruturado conforme o tipo de bloco.', verbose_name='Conteúdo')),
                ('title_level', models.PositiveSmallIntegerField(default=0, help_text='Profundidade hierárquica do título (0 = mais alto). Usado na renderização de blocos do tipo título.', validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Nível do título')),
                ('page_break_before', models.BooleanField(default=False, verbose_name='Quebrar página antes')),
                ('keep_with_previous', models.BooleanField(default=False, help_text='Evita separação deste bloco do bloco imediatamente anterior.', verbose_name='Manter com o anterior')),
                ('keep_with_next', models.BooleanField(default=False, help_text='Evita separação deste bloco do bloco imediatamente posterior.', verbose_name='Manter com o posterior')),
                ('indent_paragraph', models.BooleanField(default=False, verbose_name='Identar parágrafo')),
                ('first_line_indent', models.BooleanField(default=False, verbose_name='Recuar primeira linha')),
                ('line_spacing', models.CharField(choices=[('compact', 'Diminuir espaçamento entre linhas'), ('normal', 'Espaçamento padrão'), ('relaxed', 'Aumentar espaçamento entre linhas')], default='normal', max_length=10, verbose_name='Espaçamento entre linhas')),
                ('space_before', models.PositiveSmallIntegerField(default=0, help_text='Espaço antes do bloco, em pontos tipográficos (pt).', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Espaço antes')),
                ('space_after', models.PositiveSmallIntegerField(default=0, help_text='Espaço após o bloco, em pontos tipográficos (pt).', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Espaço após')),
            ],
            options={
                'verbose_name': 'Bloco de relatório',
                'verbose_name_plural': 'Blocos de relatório',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author_username', models.CharField(blank=True, help_text='Identificador textual preservado após exclusão da conta.', max_length=150, verbose_name='Usuário do autor (snapshot)')),
                ('author_display_name', models.CharField(blank=True, help_text='Nome exibido preservado após exclusão da conta.', max_length=255, verbose_name='Nome do autor (snapshot)')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, help_text='Desvinculado automaticamente quando a conta do autor é excluída.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('position', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='Ordem entre nós irmãos; valores decimais permitem inserção flexível.', max_digits=20, verbose_name='Posição')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='reports.reportblock', verbose_name='Bloco de conteúdo')),
                ('parent', models.ForeignKey(blank=True, help_text='Nulo para nós na raiz do relatório.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.reportnode', verbose_name='Nó pai')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Nó de relatório',
                'verbose_name_plural': 'Nós de relatório',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['report', 'parent', 'position'], name='reports_node_tree_order_idx')],
            },
        ),
    ]
