# reportline/reports/migrations/0002_report_image.py
# Generated by Django 6.0.6 on 2026-08-01 11:31

import django.db.models.deletion
import reports.models.report_image
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('image', models.ImageField(upload_to=reports.models.report_image.report_image_upload_path, verbose_name='Imagem')),
                ('width', models.PositiveIntegerField(verbose_name='Largura (px)')),
                ('height', models.PositiveIntegerField(verbose_name='Altura (px)')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome original do arquivo')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Imagem de relatório',
                'verbose_name_plural': 'Imagens de relatório',
                'ordering': ['created_at'],
            },
        ),
    ]
