# Generated by Django 6.0.6 on 2026-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Título'), ('paragraph', 'Parágrafo'), ('link', 'Link'), ('ordered_list', 'Lista numerada'), ('unordered_list', 'Lista com marcadores'), ('table', 'Tabela'), ('image', 'Imagem'), ('horizontal_rule', 'Linha horizontal')], max_length=30, verbose_name='Tipo de bloco'),
        ),
    ]
