# Generated by Django 6.0.6 on 2026-08-02 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportblock_horizontal_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_line_indent',
            field=models.BooleanField(default=True, verbose_name='Recuar primeira linha'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_captions',
            field=models.BooleanField(default=False, verbose_name='Numerar legendas'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_headings',
            field=models.BooleanField(default=True, verbose_name='Numerar títulos'),
        ),
        migrations.CreateModel(
            name='ReportUserConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number_headings', models.BooleanField(default=True, verbose_name='Numerar títulos')),
                ('number_captions', models.BooleanField(default=False, verbose_name='Numerar legendas')),
                ('first_line_indent', models.BooleanField(default=True, verbose_name='Recuar primeira linha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de laudo do usuário',
                'verbose_name_plural': 'Configurações de laudo dos usuários',
            },
        ),
    ]
