# Generated by Django 6.0.6 on 2026-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_report_user_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportuserconfig",
            name="page_layout",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Último cabeçalho e rodapé usados pelo usuário, aplicados a laudos novos.",
                verbose_name="Layout de página padrão",
            ),
        ),
    ]
