# reportline/reports/migrations/0010_alter_reportblock_line_spacing.py
# Generated by Django 6.0.6 on 2026-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportuserconfig_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportblock',
            name='line_spacing',
            field=models.CharField(choices=[('compact', 'Diminuir espaçamento entre linhas'), ('snug', 'Espaçamento 1,2 entre linhas'), ('normal', 'Espaçamento padrão'), ('relaxed', 'Aumentar espaçamento entre linhas')], default='normal', max_length=10, verbose_name='Espaçamento entre linhas'),
        ),
    ]
