# Generated by Django 6.0.6 on 2026-07-26 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicNucleus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(help_text='Identificador institucional, ex.: NPC-CAP, IC-NAT.', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('nucleus_type', models.CharField(choices=[('specialized', 'Especializado'), ('field_capital', 'Perícia criminalística — capital e Grande SP'), ('field_interior', 'Perícia criminalística — interior'), ('support', 'Apoio')], max_length=20, verbose_name='Tipo de núcleo')),
                ('organizational_center', models.CharField(choices=[('forensic_expertise', 'Centro de Perícias'), ('exams_research', 'Centro de Exames, Análises e Pesquisas'), ('logistic_support', 'Núcleo de Apoio Logístico'), ('admin_support', 'Núcleo de Apoio Administrativo')], max_length=30, verbose_name='Centro organizacional')),
                ('headquarters_city', models.CharField(blank=True, max_length=100, verbose_name='Município-sede')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Núcleo pericial',
                'verbose_name_plural': 'Núcleos periciais',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('acronym', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('parent_organization', models.CharField(help_text='Unidade administrativa à qual a instituição está subordinada.', max_length=255, verbose_name='Órgão superior')),
                ('legal_reference', models.CharField(blank=True, help_text='Ato legal ou normativo que define a estrutura organizacional.', max_length=255, verbose_name='Referência normativa')),
                ('headquarters_city', models.CharField(max_length=100, verbose_name='Município-sede')),
                ('is_provisional', models.BooleanField(default=True, help_text='Indica que os dados deste app são mantidos localmente e podem ser substituídos pelo equivalente institucional.', verbose_name='Cadastro provisório')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForensicTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(help_text='Identificador institucional, ex.: EPC-SPC, EPC-GRU.', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('headquarters_city', models.CharField(max_length=100, verbose_name='Município-sede')),
                ('is_embedded_unit', models.BooleanField(default=False, help_text='Equipe que exerce atividades junto a órgão parceiro (ex.: DHPP, DEIC, DETRAN).', verbose_name='Unidade embutida')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('nucleus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='institution_ic_sp.forensicnucleus', verbose_name='Núcleo')),
            ],
            options={
                'verbose_name': 'Equipe pericial',
                'verbose_name_plural': 'Equipes periciais',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='forensicnucleus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclei', to='institution_ic_sp.institution', verbose_name='Instituição'),
        ),
    ]
