# Generated by Django 6.0.6 on 2026-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_ic_sp', '0002_load_ic_sp_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sp_logo',
            field=models.ImageField(blank=True, help_text='Imagem exibida no cabeçalho do laudo (logo do Governo de SP).', upload_to='institution_ic_sp/logos/', verbose_name='Logo do Estado de SP'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sptc_logo',
            field=models.ImageField(blank=True, help_text='Imagem exibida no cabeçalho do laudo (logo da SPTC).', upload_to='institution_ic_sp/logos/', verbose_name='Logo da SPTC'),
        ),
    ]
