# reportline/institution_ic_sp/migrations/0004_forensicteam_address_and_more.py
# Generated by Django 6.0.6 on 2026-07-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_ic_sp', '0003_institution_sp_logo_institution_sptc_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicteam',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço físico ou referência de localização da sede.', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='forensicteam',
            name='institutional_email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail oficial da equipe pericial.', max_length=254, verbose_name='E-mail institucional'),
        ),
        migrations.AddField(
            model_name='forensicteam',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone institucional de contato da equipe.', max_length=30, verbose_name='Telefone'),
        ),
    ]
