# reportline/institution_ic_sp/migrations/0012_forensicnucleus_contact_fields.py
# Generated by Django 6.0.6 on 2026-08-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_ic_sp', '0011_institution_director_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicnucleus',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço físico ou referência de localização da sede.', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='forensicnucleus',
            name='institutional_email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail oficial do núcleo pericial.', max_length=254, verbose_name='E-mail institucional'),
        ),
        migrations.AddField(
            model_name='forensicnucleus',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone institucional de contato do núcleo.', max_length=30, verbose_name='Telefone'),
        ),
    ]
