# reportline/institution_ic_sp/migrations/0013_forensic_report_metadata.py
# Generated by Django 6.0.6 on 2026-08-06 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_ic_sp', '0012_forensicnucleus_contact_fields'),
        ('reports', '0009_reportuserconfig_page_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReportMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Metadados confirmados por fase do workflow pericial.', verbose_name='Dossiê')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_metadata', to='reports.report', verbose_name='Laudo')),
            ],
            options={
                'verbose_name': 'Metadados do laudo pericial',
                'verbose_name_plural': 'Metadados de laudos periciais',
                'ordering': ['-created_at'],
            },
        ),
    ]
